name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories
          config_timezone: America/Toronto
          # Plugins for professional look
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_achievements: yes
          plugin_notable: yes
