name: Update README

on:
  schedule:              # daily at UTC midnight (adjust as you like)
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update profile README
        uses: crazy-max/ghaction-readme-updater@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # fetch your latest blog post / tweet / now-coding section here
          # e.g., config in .github/readme-updater.yml if needed
      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README via Action" || echo "No changes to commit"
          git push
